name: Go CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21  # Specify the version of Go to use

      - name: Install dependencies
        run: go mod download

      - name: Lint the code
        run: go vet ./...

      - name: Build the library
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...